version: '3'
services:
  node:
    image: node:15.11.0-alpine3.10
    expose:
      - "3000"
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    working_dir: /app
    stdin_open: true
    tty: true
    depends_on:
      - db
    command: npm start

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: brenoneves

  adminer:
    image: adminer
    restart: always
    ports:
      - 3000:3000